# Generated by Django 5.2.3 on 2025-06-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='mood',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
